### PR TITLE
Token parse

### PR DESCRIPTION
**Pull request by lvn-ryu**
needed to allow [tokenfactory denoms](https://docs.osmosis.zone/osmosis-core/modules/tokenfactory/#createdenom)

also ran out of gas, so increased the multiplier a bit

### CODE REVIEW

**Comment by lvn-rusty-dragon** [comment]
This broke the testsuite. I'm not sure if the tests need to be relaxed or the code is wrong. I have a feeling we _do_ need a little more logic than just allowing any combination of ASCII lowercase letters, digits, and slashes. Do we know the rules for a valid denom?

**Comment by lvn-ryu** [comment]
Whups! I'll fix the test and ping for re-review later. I am not sure what the absolute rules are, but tokenfactory denoms allow lowercase, uppercase, numbers, and slashes

**Comment by lvn-ryu** [comment]
fixed, and switched to use RegEx so if we have better rules we can hopefully just change that one var

**Comment by lvn-ryu** [comment]
@lvn-rusty-dragon I've moved the multiplier back from 1.5 to 1.3 as discussed in sync, will push a separate branch without a PR to have the multiplier for temp dev needs

**Review by lvn-rusty-dragon — APPROVED** [review]

**Pull request merged**
